### ISSUE TITLE
partial does not load in template

### ISSUE THREAD

**Issue by skaltenegger** [deepsweet/mustache-loader#22]
Hey there,

I'm including the mustache-loader with the noShortcut option in my webpack-config and loading the templates as follows:
`const articlecardTemplate = require('./components/articlecard.mustache');
const userTemplate = require('./components/user.mustache');
const compiled = articlecardTemplate.render({ foo: 'bar' }, {partial: userTemplate});
`

However, the content of the userTemplate does not show up in the articlecardTemplate although I'm including it via `{{> userTemplate}}` in my articlecardTemplate.

Any hints/help on this is very much appreciated.
Thanks,
Stefan

**Comment by baderbuddy** [comment]
Hi @skaltenegger it took me a little while to get to my test project in order to try this out, sorry about that.

It looks like partials are working okay, but you passed in the name of your partial as "partial" instead of "userTemplate" So what you wanted was probably more like. `const compiled = articlecardTemplate.render({ foo: 'bar' }, {userTemplate: userTemplate});`

**Comment by baderbuddy** [comment]
I haven't heard back so I'll assume this is closed
